build_requires: {}
conflicts: {}
dist_name: Plugins-SuperDateTime-Plugin.par
distribution_type: par
dynamic_config: 0
generated_by: 'PAR::Packer version 0.973
license: unknown
par:
  clean: 0
  signature: ''
  verbatim: 0
  version: 0.976
